server.port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      - id: service1
        uri: lb://service1
        predicates:
        - Path=/s1/**
        filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - RewritePath=/s1/(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
reactor.ipc.netty: DEBUG