server.port: 8081
spring:
  application:
    name: service1
endpoints:
  prometheus:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus